const test = require('node:test'); const assert = require('node:assert/strict'); const fs = require('node:fs'); const path = require('node:path');
const root = path.join(__dirname, '..');
test('Home achievement link uses deployment-relative path', () => { const html = fs.readFileSync(path.join(root, 'public/index.html'), 'utf8'); assert.doesNotMatch(html, /\.\.\/public\/page\/achievement\.html/); assert.match(html, /page\/achievement\.html/); });
test('Activity upcoming list only uses valid start dates and sorts ascending', () => { const js = fs.readFileSync(path.join(root, 'public/js/activity-dynamic.js'), 'utf8'); assert.match(js, /new Date\(activity\.start_date\)/); assert.match(js, /\.sort\(\(a, b\) => a\.date - b\.date\)/); });
test('Personnel update preserves omitted fields and checks delete response', () => { const route = fs.readFileSync(path.join(root, 'src/routes/team.js'), 'utf8'); const js = fs.readFileSync(path.join(root, 'public/js/admin-personnel.js'), 'utf8'); assert.match(route, /const merged = \{ \.\.\.existing, \.\.\.req\.body \}/); assert.match(js, /!response\.ok \|\| !data\.success/); });
test('CMS achievement edits preserve images when image field is omitted', () => { const route = fs.readFileSync(path.join(root, 'src/routes/cmsContent.js'), 'utf8'); assert.match(route, /imageProvided/); assert.match(route, /if \(payload\.imageProvided\)/); });
test('Achievement renderer escapes fields and rejects unsafe image URLs', () => { const js = fs.readFileSync(path.join(root, 'public/js/achievement-dynamic.js'), 'utf8'); assert.match(js, /safeImageUrl/); assert.match(js, /escapeHtml\(ach\.title/); assert.match(js, /String\(ach\.description \|\| ''\)/); });
test('PDF local resource resolver prevents path traversal', () => { const renderer = require('../src/services/pdfRenderer'); const pathOutside = renderer.resolveWithinRoot(path.join(root, 'uploads'), '../secret.txt'); assert.equal(pathOutside, null); });
test('Achievement stylesheet contains no truncated card selector', () => { const css = fs.readFileSync(path.join(root, 'public/css/achievement.css'), 'utf8'); assert.doesNotMatch(css, /(^|\n)\.card-\s*(\n|$)/); });
